# Generated by Django 5.2.14 on 2026-09-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('user_id', models.BigIntegerField()),
                ('activity_date', models.DateField()),
                ('actual_risk', models.CharField(max_length=10, null=True)),
                ('predicted_risk', models.CharField(max_length=10, null=True)),
                ('prediction_correct', models.IntegerField(null=True)),
                ('probability_high', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('probability_medium', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('probability_low', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
            ],
            options={
                'db_table': 't_classification_result',
                'ordering': ['user_id', 'activity_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorrelationMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_x', models.CharField(max_length=50)),
                ('feature_y', models.CharField(max_length=50)),
                ('corr_value', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
            ],
            options={
                'db_table': 't_correlation_matrix',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyStress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('activity_date', models.DateField()),
                ('stress_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('risk_level', models.CharField(max_length=10, null=True)),
                ('hr_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sleep_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('active_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('sedentary_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('trend_label', models.CharField(max_length=20, null=True)),
                ('score_7day_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 't_daily_stress',
                'ordering': ['user_id', 'activity_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeatureImportance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=50)),
                ('importance', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('rank_order', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_feature_importance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('avg_intensity', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('avg_calories', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('avg_steps', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('record_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 't_hourly_pattern',
                'ordering': ['user_id', 'hour_of_day'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LearningCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('train_size', models.IntegerField()),
                ('train_score', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('test_score', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
            ],
            options={
                'db_table': 't_learning_curve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'db_table': 't_model_metrics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('activity_date', models.DateField()),
                ('stress_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_7day_avg', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('score_change_rate', models.DecimalField(decimal_places=4, max_digits=8, null=True)),
                ('trend_label', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 't_trend_analysis',
                'ordering': ['user_id', 'activity_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cluster_id', models.IntegerField(null=True)),
                ('cluster_label', models.CharField(max_length=20, null=True)),
                ('avg_stress_score', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_sleep_efficiency', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('avg_active_minutes', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('avg_resting_hr', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('avg_sedentary_ratio', models.DecimalField(decimal_places=4, max_digits=5, null=True)),
                ('risk_level', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 't_user_profile',
                'managed': False,
            },
        ),
    ]
